name: Backend CI

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy source code từ repository
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Cài Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # 3. Cài dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Kiểm tra lint
      - name: Run lint
        run: npm run lint

      # 5. Chạy unit test
      - name: Run tests
        run: npm test

      # 6. Build NestJS
      - name: Build application
        run: npm run build